"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

# Started on 25th March 2015 18:16 PM

first_number = 1
second_number = 2

fibonacci_number = 0


def next_number(x, y):
    return x+y

highest_number = 2
x = 1
y = 2
count = 0

while highest_number < 4000000:
    z = next_number(x, y)
    x = y
    y = z
    highest_number = y
    print(x)
    if x % 2 == 0:
        count += x

print(count)

# Completed on 25th March 2015 18:33 PM